# Generated by Django 4.2.2 on 2023-06-08 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 13, 36, 6, 783716, tzinfo=datetime.timezone.utc)),
        ),
    ]
